export const states = {
  init: "_init",
  active: "_active",
  fixed: "_fixed",
  scroll: "_scroll",
  open: "_open",
  hover: "_hover",
  focus: "_focus",
  disabled: "_disabled",
  select: "_select",
  error: "_error",
  required: "_required",
  animate: "_animate",
  success: "_success",
  hidden: "_hidden",
  show: "_show",
  checked: "_checked",
  empty: "_empty",
  target: "_target",
  favorite: "_favorite",
  cart: "_cart",
  valid: "_valid",
};
